### ISSUE TITLE
example1无任何标签显示

### ISSUE THREAD

**Issue by serse01** [grapheco/InteractiveGraph-neo4j#7]
我按照您的方式配置好了interactiveGraph-neo4j和interactiveGraph，但是我在访问http://localhost:8080/igraph/example1.html的时候没有任何节点出现。neo4j和interactiveGraph-neo4j和interactiveGraph都在本机，但在访问http://localhost:8080/igraph/example1.html时没有任何表情显示，且日志报错为"POST /graphserver/connector-bolt?command=init HTTP/1.1" 500 13026

**Comment by serse01** [comment]
我怀疑是由于interactiveGraph-neo4j未配置成功导致的，但是您在文章中说出现字就算成功，所以我不知道是否算配置成功了
![1612155893(1)](https://user-images.githubusercontent.com/65155615/106417102-24c5ab80-648e-11eb-9a1d-f300e068164a.jpg)

**Comment by serse01** [comment]
您好！我在试用example1的时候使用interactivegraph-0.0.3中自带的地址39.107.244.223:7687是可以访问成功，出现节点的，但是切换回本地地址时就访问失败，没有任何节点出现（neo4j，interactivegraph及interactivegraph-neo4j均在一台设备，且bolt节点端口为7687),请问这是什么原因造成的呢，十分希望得到您的帮助！谢谢！

**Comment by HC-teemo** [comment]
检查Neo4j用户名密码是否正确。如果没问题，请提供下server日志的报错信息

**Comment by serse01** [comment]
> 检查Neo4j用户名密码是否正确。如果没问题，请提供下server日志的报错信息

Neo4用户名和密码均正确，server报错信息为
01-Feb-2021 17:01:42.896 严重 [http-nio-8080-exec-4] org.apache.catalina.core.ApplicationContext.log Servlet[connector1]的Servlet.init（）引发异常
	org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.grapheco.server.neo4j.Neo4jSetting#0' defined in class path resource [neo4j-base.xml]: Cannot create inner bean 'org.grapheco.server.neo4j.Neo4jGraphMetaDBInMemory#7226db83' of type [org.grapheco.server.neo4j.Neo4jGraphMetaDBInMemory] while setting bean property 'graphMetaDB'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.grapheco.server.neo4j.Neo4jGraphMetaDBInMemory#7226db83' defined in class path resource [neo4j-base.xml]: Invocation of init method failed; nested exception is org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database
		at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:282)
		at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:121)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1456)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1197)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:537)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
		at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
		at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
		at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
		at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
		at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:700)
		at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
		at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
		at org.grapheco.server.ConnectorServlet.init(ConnectorServlet.scala:58)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1134)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1089)
		at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:761)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:135)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:830)
	Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.grapheco.server.neo4j.Neo4jGraphMetaDBInMemory#7226db83' defined in class path resource [neo4j-base.xml]: Invocation of init method failed; nested exception is org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
		at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:269)
		... 33 more
	Caused by: org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database
		at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:44)
		at org.neo4j.driver.internal.async.HandshakeHandler.channelInactive(HandshakeHandler.java:84)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
		at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1010)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
		at org.neo4j.driver.internal.shaded.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
		at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		... 1 more
01-Feb-2021 17:01:42.896 严重 [http-nio-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke 分配异常的servlet [connector1]
	org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database
		at org.neo4j.driver.internal.util.ErrorUtil.newConnectionTerminatedError(ErrorUtil.java:44)
		at org.neo4j.driver.internal.async.HandshakeHandler.channelInactive(HandshakeHandler.java:84)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
		at org.neo4j.driver.internal.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
		at org.neo4j.driver.internal.shaded.io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1010)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
		at org.neo4j.driver.internal.shaded.io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
		at org.neo4j.driver.internal.shaded.io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1409)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
		at org.neo4j.driver.internal.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:927)
		at org.neo4j.driver.internal.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
		at org.neo4j.driver.internal.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
		at org.neo4j.driver.internal.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by HC-teemo** [comment]
`org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database`

从这段报错信息看来是在连接数据库的时候产生了错误。建议
- 重新启动或重新安装neo4j
- 使用server版本neo4j
- 检查网络情况

**Comment by serse01** [comment]
> `org.neo4j.driver.v1.exceptions.ServiceUnavailableException: Connection to the database terminated. This can happen due to network instabilities, or due to restarts of the database`
> 
> 从这段报错信息看来是在连接数据库的时候产生了错误。建议
> 
> * 重新启动或重新安装neo4j
> * 使用server版本neo4j
> * 检查网络情况

我这边重装了neo4j社区server版4.2.6，4.2.1，4.0.6，3.5.26都是报这个错误，而且网络情况是没有问题的，这应该怎么办呢，我应该装一个桌面版试试吗？

**Comment by HC-teemo** [comment]
由于该错误发生在neo4j端，我只能提供一些建议。你可以参考这篇[文章](https://blog.csdn.net/qinweijing_3360/article/details/102625186)看看是否有效，或者去搜索引擎搜索该错误信息。

**Comment by serse01** [comment]
> 由于该错误发生在neo4j端，我只能提供一些建议。你可以参考这篇[文章](https://blog.csdn.net/qinweijing_3360/article/details/102625186)看看是否有效，或者去搜索引擎搜索该错误信息。

非常感谢，我更换为3.5.26之后发生的错误是为更换密码，现在已经可以成功显示，但是好像4版本的neo4j都不支持interactiveGraph-neo4j和interactiveGraph，总是会在访问数据库时出错

**Comment by serse01** [comment]
问题已解决，非常感谢

**Comment by HC-teemo** [comment]
> > 由于该错误发生在neo4j端，我只能提供一些建议。你可以参考这篇[文章](https://blog.csdn.net/qinweijing_3360/article/details/102625186)看看是否有效，或者去搜索引擎搜索该错误信息。
> 
> 
> 
> 非常感谢，我更换为3.5.26之后发生的错误是为更换密码，现在已经可以成功显示，但是好像4版本的neo4j都不支持interactiveGraph-neo4j和interactiveGraph，总是会在访问数据库时出错

是的，4.x版本暂未适配

**Comment by serse01** [comment]
> > > 由于该错误发生在neo4j端，我只能提供一些建议。你可以参考这篇[文章](https://blog.csdn.net/qinweijing_3360/article/details/102625186)看看是否有效，或者去搜索引擎搜索该错误信息。
> > 
> > 
> > 非常感谢，我更换为3.5.26之后发生的错误是为更换密码，现在已经可以成功显示，但是好像4版本的neo4j都不支持interactiveGraph-neo4j和interactiveGraph，总是会在访问数据库时出错
> 
> 是的，4.x版本暂未适配完全，我们会尽快解决

我想问一下可以显示本地图片吗

**Comment by HC-teemo** [comment]
不能访问本地，你可以把图片文件放在自己的server上并提供url

**Comment by serse01** [comment]
> 不能访问本地，你可以把图片文件放在自己的server上并提供url

好的，谢谢

**Comment by serse01** [comment]
还有一个问题就是可以放视频上去吗?
